In [8]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [9]:
env = gym.make("FrozenLake-v0")

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [11]:
rewards_all_episodes = []

# Learning process
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        #Update Q-table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("************Average reward per thousand episodes************\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
# Print updated Q-table
print("\n\n**********Q-table**********\n")
print(q_table)

************Average reward per thousand episodes************

1000 :  0.03800000000000003
2000 :  0.21600000000000016
3000 :  0.3720000000000003
4000 :  0.5350000000000004
5000 :  0.6420000000000005
6000 :  0.6580000000000005
7000 :  0.6490000000000005
8000 :  0.6870000000000005
9000 :  0.7060000000000005
10000 :  0.6520000000000005


**********Q-table**********

[[0.61553914 0.45710958 0.46198889 0.45223235]
 [0.32565446 0.36341581 0.30829334 0.49799943]
 [0.38634978 0.39418649 0.37883946 0.43417896]
 [0.23079997 0.32361428 0.32181018 0.41828409]
 [0.63288607 0.33747937 0.4520764  0.30094291]
 [0.         0.         0.         0.        ]
 [0.26967436 0.10650287 0.15308784 0.13943398]
 [0.         0.         0.         0.        ]
 [0.43377744 0.32276937 0.46138944 0.67209854]
 [0.4272109  0.72987152 0.48595468 0.45418   ]
 [0.74207624 0.29619088 0.32124984 0.3434841 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.32153368 0.46847225

In [12]:
#predict the performance of the learning model
for episode in range(3):
    state = env.reset()
    done = False
    print("************EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(2)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("You reach the goal!")
                time.sleep(3)
            else:
                print("You fell through a hole!")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
You reach the goal!
